apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting
  labels:
    app: result
spec:
  type: ClusterIP
  ports:
    - name: "result-service"
      port: 80
      targetPort: 80
  selector:
    app: result