apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: voting
  labels:
    app: vote
spec:
  type: LoadBalancer
  ports:
    - name: "vote-service"
      # external port to expose
      port: 80
      # internal port of the application running in the pod
      targetPort: 80
  selector:
    app: vote