# This is a sample pod definition for using SecretProviderClass and the user-assigned identity to access your key vault

kind: Pod
apiVersion: v1
metadata:
  name: sc-demo-keyvault-csi
  namespace: voting
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - "/bin/sleep"
        - "10000"
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              # name of k8s secret (find in secretObjects in SecretProviderClass)
              name: voting-secrets 
              # key name inside Key Value
              key: db-password    
      # need to mount secret volume defined below
      volumeMounts:
        - name: secrets-mount-volume
          mountPath: "/mnt/secrets-store"
          readOnly: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi

  # volue need to defined, to read secret from secretProviderClass  
  volumes:
    - name: secrets-mount-volume
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "voting-secret-provider"