apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: voting-secret-provider
  namespace: voting
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   # because AKS uses Managed Identity
    # can find this from key value access control (IAM) in azure portal (client ID)
    userAssignedIdentityID: "674ef7a7-0b29-4cc4-a87e-555e7a2ae28d"
    keyvaultName: "lab-secret"  # 👈 replace with your actual Key Vault name
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
    # azure tenant id, can find in microsoft entra ID
    tenantId: "65c5b306-656f-4615-8a91-06294bf37a9f"
  
  secretObjects:                      # optional: create Kubernetes secret objects
  - secretName: voting-secrets        # name of the Kubernetes secret
    type: Opaque
    data:
    - objectName: db-password        # name of the object in Key Vault
      key: db-password               # key to store in Kubernetes secret