services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8205:8025"  # Web UI
      - "1025:1025"  # SMTP
    restart: unless-stopped
    environment:
      - MP_WEBHOOK_URL=
    volumes:
      - mailpit_data:/data

volumes:
  mailpit_data:

