apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-lab-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   # because AKS uses Managed Identity
    # can find this from key value access control (IAM) in azure portal (client ID)
    userAssignedIdentityID: "3e4694d3-546a-4102-8624-c7db0e5858d2"
    keyvaultName: "my-lab"  # 👈 replace with your actual Key Vault name
    cloudName: ""
    objects: |
      array:
        - |
          objectName: ghcr-secret
          objectType: secret
    # azure tenant id, can find in microsoft entra ID
    tenantId: "65c5b306-656f-4615-8a91-06294bf37a9f"
  
  secretObjects:                      # optional: create Kubernetes secret objects
  - secretName: my-lab-secrets        # name of the Kubernetes secret
    type: kubernetes.io/dockerconfigjson
    data:
    - objectName: ghcr-secret       # name of the object in Key Vault
      key: .dockerconfigjson               # key to store in Kubernetes secret