apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    app: {{ .Values.nginx.labels.app }}
spec:
  type: NodePort
  ports:
    - name: nginx-service
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      nodePort: {{ .Values.nginx.nodePort }}
  selector:
    app: {{ .Values.nginx.labels.app }}